stages:
  - test

variables:
  PYTHONPATH: "${PYTHONPATH}:${CI_PROJECT_DIR}"

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s utils -p "test_*.py"
